#!/bin/bash
#SBATCH -o OUT/seq/seq-%j.out
#SBATCH -e OUT/seq/seq-%j.err
#SBATCH --ntasks=1
#SBATCH --partition=new-nodo.q

module purge
module load openmpi/4.1.1

# ARGUMENTS
NUM_EPOCHS=${1:-10}
NUM_NEURONS=${2:-250}
REPEAT=${3:-1}

# METADATA
echo "---"
echo "date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "job_id: $SLURM_JOB_ID"
echo "repeat: $REPEAT"
echo "server: Wilma"
echo "partition: $SLURM_JOB_PARTITION"
echo "nprocs: $SLURM_NTASKS"
echo "num_epochs: $NUM_EPOCHS"
echo "num_neurons: $NUM_NEURONS"
echo "---"

# NETEJA
rm -f exec *.o common/*.o configuration/*.o layer/*.o randomizer/*.o initialize/*.o training/*.o
rm -rf ./*.so ./*.a

# COMPILACIÓ
mpicc -O3 \
    main.c \
    common/common.c \
    configuration/config.c \
    layer/layer.c \
    randomizer/randomizer.c \
    initialize/initialize.c \
    training/training.c \
    -o exec \
    -lm

# EXECUCIÓ
for ((i=1; i<=$REPEAT; i++)); do
    echo ">>>>>>>>>>>> $i"
    mpirun -np $SLURM_NTASKS ./exec $NUM_EPOCHS $NUM_NEURONS
done
echo ">>>>>>>>>>>> -"
