#!/bin/bash
#SBATCH --job-name=MPI_TEST002
#SBATCH --ntasks=96
#SBATCH --ntasks-per-node=8
#SBATCH -N 12
#SBATCH --partition=nodo.q

#SBATCH -o /home/alumnos/capmc/capmc-1/Escritorio/FFNN-SourceCode/OUT/slurm-%j.out
#SBATCH -e /home/alumnos/capmc/capmc-1/Escritorio/FFNN-SourceCode/OUT/slurm-%j.err

module purge
module load openmpi/4.1.1

# ARGUMENTS
TEST_NUM="${1:-002}"
FLAGS_RAW="$2"
REPEAT="${3:-1}"
SUBFOLDER="${4:-A}"
TRAINING_FILE="${5:-training/training.c}"
CONFIG_FILE="${6:-configuration/configfile.txt}"

# DIRECTORI BASE
BASE_DIR="/home/alumnos/capmc/capmc-1/Escritorio/FFNN-SourceCode"

# DIRECTORI OUTPUT
OUTPUT_DIR="$BASE_DIR/TESTS/OPENMPI/TEST_${TEST_NUM}/OUT/$SUBFOLDER"
OUTPUT_FILE="$OUTPUT_DIR/out_${SLURM_JOB_ID}.out"
ERRORS_FILE="$OUTPUT_DIR/err_${SLURM_JOB_ID}.out"
mkdir -p "$OUTPUT_DIR"

# REDIRECT
exec 1> "$OUTPUT_FILE"
exec 2> "$ERRORS_FILE"

# CANVI A BASE DIR
cd "$BASE_DIR" || { echo "ERROR: Cannot enter $BASE_DIR"; exit 1; }

# FLAGS
if [ -n "$FLAGS_RAW" ]; then
    FLAGS="-D${FLAGS_RAW//,/ -D}"
    NP=$SLURM_NTASKS
else
    FLAGS=""
    NP=1
fi

# EXTRAURE PARÀMETRES DEL CONFIG FILE
NUM_EPOCHS=$(grep 'num_epochs=' "$CONFIG_FILE" | cut -d'=' -f2)
NUM_NEURONS=$(grep 'layer=' "$CONFIG_FILE" | sed -n '2p' | cut -d'=' -f2)

# METADATA
echo "---"
echo "test_number: $TEST_NUM"
echo "date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "job_id: $SLURM_JOB_ID"
echo "output_directory: $OUTPUT_DIR"
echo "output_file: out_${SLURM_JOB_ID}.out"
echo "errors_file: err_${SLURM_JOB_ID}.out"
echo "compilation_flags: $FLAGS"
echo "number_executions: $REPEAT"
echo "server: Wilma"
echo "partition_file: $SLURM_JOB_PARTITION"
echo "num_processes: $NP"
echo "num_nodes: $SLURM_JOB_NUM_NODES"
echo "num_epochs: $NUM_EPOCHS"
echo "num_neurons: $NUM_NEURONS"
echo "config_file: $CONFIG_FILE"
echo "---"

# NETEJA DE FITXERS COMPILATS ANTERIORS
echo "Cleaning previous builds..."
rm -f exec *.o common/*.o configuration/*.o layer/*.o randomizer/*.o initialize/*.o training/*.o
rm -rf ./*.so ./*.a


# COMPILACIÓ
mpicc -O3 \
    $FLAGS \
    main.c \
    common/common.c \
    configuration/config.c \
    layer/layer.c \
    randomizer/randomizer.c \
    initialize/initialize.c \
    $TRAINING_FILE \
    -o exec \
    -lm

if [ $? -ne 0 ]; then
    echo "ERROR: Compilation failed"
    exit 1
fi

# EXECUCIÓ
for ((i=1; i<=$REPEAT; i++)); do
    echo "#START:$i"
    if [ $NP -eq 1 ]; then
        ./exec "$CONFIG_FILE"
    else
        mpirun -np $SLURM_NTASKS ./exec "$CONFIG_FILE"
    fi
    echo "#END:$i"
done