sbatch TESTS/TEST_004/TEST_004.sub NO_FEED_INPUT
sbatch TESTS/TEST_004/TEST_004.sub FEED_INPUT

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_FORWARD_PROP_LAYERS
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_FORWARD_PROP_LAYERS

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_BACK_PROP_ERRORS
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_BACK_PROP_ERRORS

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_BACK_PROP_OUTPUT_LAYER
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_BACK_PROP_OUTPUT_LAYER

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_BACK_PROP_HIDDEN_LAYERS
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_BACK_PROP_HIDDEN_LAYERS

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_UPDATE_WEIGHTS_WEIGHTS
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_UPDATE_WEIGHTS_WEIGHTS

sbatch TESTS/TEST_004/TEST_004.sub NO_TRAINING_UPDATE_WEIGHTS_BIASES
sbatch TESTS/TEST_004/TEST_004.sub TRAINING_UPDATE_WEIGHTS_BIASES

